#define RLV	0x8FFF	
//reload value should be between 4k to 64k … see the datasheet for details

typedef struct {
	int delay;
} TIM_DEV;

static TIM_DEV TimDev;
static char buffer[100];	
static irqreturn_t INTHandler (int irq,void *TimDev)
{

	
	unsigned TimerINTControl;
	unsigned TimerCNTB;
	unsigned TimerCMPB;	
	int TMP;
	
	// Read Timer Registers
	TimerINTControl = readl(S3C_TINT_CSTAT);
	TimerCNTB = readl(S3C_TCNTB(0));
	TimerCMPB = readl(S3C_TCMPB(0));
	
	for (int i=0;i<5;i++){
	LED(i,4);
                              }
	// Your logic to send the frame values to port Q (16 rows) and E (8 columns) 
// You may use LED (x, y) function as we did in PIC-based assignment



	TimerINTControl |= S3C_TINT_CSTAT_T0INT;
	writel(TimerINTControl, S3C_TINT_CSTAT);	
	writel(RLV, S3C_TCNTB(0));
	writel(RLV, S3C_TCMPB(0)); 
	
	return IRQ_HANDLED;
}

void LED(unsigned int x, unsigned int y) 
{
	unsigned Port_Q_Dat;
	unsigned Port_E_Dat;	
	Port_E_Dat = readl(S3C64XX_GPEDAT);
	Port_Q_Dat = readl(S3C64XX_GPQDAT);
	
	Port_E_Dat |= (0x1 << (4));
	
	writel(Port_E_Dat, S3C64XX_GPEDAT);
	Port_E_Dat = readl(S3C64XX_GPEDAT);
	
	if (test_bit(0,(const volatile long unsigned int *)&x)) {
		Port_E_Dat |= (0x1 << (1));
	} else {
		Port_E_Dat &= ~(0x1 << (1));
	}	
	
	if (test_bit(1,(const volatile long unsigned int *)&x)) {
		Port_E_Dat |= (0x1 << (2));
	} else {
		Port_E_Dat &= ~(0x1 << (2));

	}	
	
	if (test_bit(2,(const volatile long unsigned int *)&x)) {
		Port_E_Dat |= (0x1 << (3));
	} else {
		Port_E_Dat &= ~(0x1 << (3));

	}
	
	if (test_bit(0,(const volatile long unsigned int *)&y)) {
		Port_Q_Dat |= (0x1 << (1));
	} else {
		Port_Q_Dat &= ~(0x1 << (1));
	}
	
	if (test_bit(1,(const volatile long unsigned int *)&y)) {
		Port_Q_Dat |= (0x1 << (2));
	} else {
		Port_Q_Dat &= ~(0x1 << (2));
	}
	
	if (test_bit(2,(const volatile long unsigned int *)&y)) {
		Port_Q_Dat |= (0x1 << (3));
	} else {
		Port_Q_Dat &= ~(0x1 << (3));
	}
	
	if (test_bit(3,(const volatile long unsigned int *)&y)) {
		Port_Q_Dat |= (0x1 << (4));
	} else {
		Port_Q_Dat &= ~(0x1 << (4));
	}	
	
	Port_E_Dat &= ~(0x1 << (4)); // This is to put EN-port to low

	writel(Port_E_Dat, S3C64XX_GPEDAT);
	writel(Port_Q_Dat, S3C64XX_GPQDAT);
}

static ssize_t MyWrite (struct file *filp, const char * buf, size_t count, loff_t *f_pos) {
	// write a function similar to mywrite () of misc. char device driver
	// it will save the frame string generated by QT app in a temporary buffer
	
//static ssize_t MyWrite (struct file *filp, const char * buf, size_t count, loff_t *f_pos) {
	//char buffer[100];	
	int ret;
	LED(5,7);
	ret = copy_from_user(&buffer,buf,count);
	*f_pos+=count;
	buffer[count] = '\0';
	printk("%s",buffer); 
	if (buffer[count-1]!='\n') printk("\n");

	return count;

}
	
	
}

static struct file_operations dev_fops = {
	owner:		THIS_MODULE,
	write:		MyWrite,	
};

static struct miscdevice misc = {
	.minor	= MISC_DYNAMIC_MINOR,
	.name	= DEVICE_NAME,
	.fops	= &dev_fops,
};

static int __init dev_init(void)
{
	int ret;
	unsigned TimerControl;
	unsigned TimerINTControl;
	unsigned TimerCNTB;
	unsigned TimerCMPB;
	unsigned TimerCFG1;
	
	
	
	unsigned Port_Q_Dat;
	unsigned Port_Q_Con;
	unsigned Port_E_Dat;
	unsigned Port_E_Con;
	
	Port_E_Dat = readl(S3C64XX_GPEDAT);
	Port_E_Con = readl(S3C64XX_GPECON);
	Port_Q_Dat = readl(S3C64XX_GPQDAT);
	Port_Q_Con = readl(S3C64XX_GPQCON);
	// changes made here
	Port_E_Dat=00010001000100010001;
	Port_Q_Dat=00010001000100010001;
	Port_E_Con=00000000000000000000;
	Port_Q_Con=00000000000000000000;
	
	// Write your logic to set Port Q and E as OUTPUT ports
// Write your logic to set all pins of Port Q and E (except EN) low, so that LED matrix starts with all LEDs turned off
	Port_E_Dat=
	writel(Port_E_Dat, S3C64XX_GPEDAT);
	writel(Port_E_Con, S3C64XX_GPECON);
	writel(Port_Q_Dat, S3C64XX_GPQDAT);
	writel(Port_Q_Con, S3C64XX_GPQCON);
	
// The following code is similar to IRQ Handler INIT function plus we are 
// registering our driver to the misc device layer

TimerControl 		= readl(S3C_TCON);
	TimerINTControl 	= readl(S3C_TINT_CSTAT);
	TimerCNTB 		= readl(S3C_TCNTB(0));
	TimerCMPB 		= readl(S3C_TCMPB(0));
	
	TimerCFG1 		= readl(S3C_TCFG1);
	
	TimerCFG1 		&= ~(S3C_TCFG1_MUX0_MASK);
	
	TimerCNTB 		= RLV;
	TimerCMPB 		= RLV;
	
	writel(TimerCNTB, S3C_TCNTB(0));
	writel(TimerCMPB, S3C_TCMPB(0));
	writel(TimerCFG1, S3C_TCFG1);
	
	TimerControl 		|= S3C_TCON_T0MANUALUPD;
	
	TimerINTControl 	|= S3C_TINT_CSTAT_T0INTEN;
	
	writel(TimerControl, S3C_TCON);
	writel(TimerINTControl, S3C_TINT_CSTAT);
	
	TimerControl 		= readl(S3C_TCON);
	
	TimerControl		|= S3C_TCON_T0RELOAD;
	TimerControl 		&= ~S3C_TCON_T0MANUALUPD; 
	TimerControl 		|= S3C_TCON_T0START;
	
	writel(TimerControl, S3C_TCON);

	ret = request_irq(IRQ_TIMER0, INTHandler, IRQF_SHARED, DEVICE_NAME, &TimDev);
	if (ret) {
		return ret;
	}
	ret = misc_register(&misc);

	printk (DEVICE_NAME"\tinitialized\n");
	return ret;
}

static void __exit dev_exit(void)
{
	free_irq(IRQ_TIMER0, &TimDev);
	misc_deregister(&misc);
}
module_init(dev_init);
module_exit(dev_exit);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("EE522 Embedded Systems 2016 batch");
